import { NPC_NAME_CATALOG } from '../data/npcNameCatalogue';
import { EVENT_HABITAT_OPTIONS } from '../data/habitatOptions';

class NpcGenerator {
  static HABITAT_OPTIONS = EVENT_HABITAT_OPTIONS;

  static npcOptions = {
    hostility: [
      { attitude: 'supportive', socialChecks: 'very easy', dc: 5 },
      { attitude: 'friendly', socialChecks: 'easy', dc: 10 },
      { attitude: 'indifferent', socialChecks: 'medium', dc: 15 },
      { attitude: 'suspicious', socialChecks: 'hard', dc: 20 },
      { attitude: 'hostile', socialChecks: 'very hard', dc: 25 },
    ],
    motivation: ['money', 'help', 'survival', 'status', 'relationships', 'knowledge', 'power', 'revenge', 'ideology'],
    physicalQuirk: [
      'has a silver tooth',
      'keeps one eye half-closed',
      'has a noticeable limp',
      'wears mismatched gloves',
      'has burn scars on one hand',
      'sports elaborate braided hair',
      'has a low gravelly voice',
      'has ink-stained fingers',
      'wears a cracked monocle',
      'always smells of lavender oil',
      'has a chipped tusk',
      'wears one boot taller than the other',
      'has a faded military tattoo',
      'has a missing fingertip',
      'wears too many rings',
      'has a permanent squint',
      'has a shaved stripe through one eyebrow',
      'has frostbitten ears',
      'has soot-blackened nails',
      'has a tiny bell sewn into their cloak',
      'has a carved wooden prosthetic hand',
      'has a scar shaped like a crescent moon',
      'has a broken nose set crooked',
      'has a patchwork coat of many fabrics',
      'has one gold-painted fingernail',
      'has mismatched eye colors',
      'has a deep smoker cough',
      'has hands calloused like stone',
      'has a constantly twitching left eye',
      'has a jagged ear notch',
      'has a voice that cracks unpredictably',
      'has bright dye-stained hair tips',
      'has knuckles wrapped in old linen',
      'has a faint glow in their pupils',
      'has a permanently hoarse whisper',
      'has a tattooed map on one forearm',
      'has braided beard beads',
      'has a chipped horn',
      'has a ritual scar across the scalp',
      'has a missing canine tooth',
      'has wrists covered in old rope marks',
      'has an ever-present runny nose',
      'has a heavy perfume that masks smoke',
      'has a long burn mark down one arm',
      'has dirt permanently under the nails',
      'has a ceremonial face paint stripe',
      'has a coin embedded in a necklace scar',
      'has an iron brace on one knee',
      'has a velvet eyepatch',
      'has a habit of cracking every knuckle loudly',
      'has a hand tremor when idle',
      'has a sun-weathered leathered face',
      'has a polished bone hairpin',
      'has a limp that vanishes when running',
      'has a serpentine tattoo around the neck',
      'has an old arrow scar in the shoulder',
      'has thick spectacles with cracked lenses',
      'has chalk dust on every sleeve',
      'has long pianist fingers with blunt nails',
      'has a soot-smudged jawline',
      'has a braided cord tied to one wrist',
      'has a ceremonial nose ring',
      'has a permanent grin line scar',
      'has a half-burned cloak hem',
      'has one sleeve pinned at the elbow',
      'has polished metal teeth caps',
      'has a pitted pox-marked complexion',
      'has wind-chapped lips year-round',
      'has a tiny rune branded behind one ear',
      'has a chain of tiny charms around one ankle',
      'has a wolf bite scar on the calf',
      'has a shaved head except for one braid',
      'has bright freckles across the nose',
      'has cracked, calloused heels',
      'has hands that are always cold',
      'has a voice that rumbles like distant thunder',
      'has permanently singed eyebrows',
      'has a glove covering a tattooed palm sigil',
      'has faint blue veins that stand out in moonlight',
      'has stained teeth from herbal chewing',
      'has a perfume of pine resin and smoke',
      'has an ornate cane despite no obvious injury',
      'has a stitched seam in one ear',
      'has heavy rings in both ears',
      'has a small ritual brand on the wrist',
      'has a weathered sailor knot tattoo',
      'has a jagged scar over one collarbone',
      'has a polished stone inlaid in a belt clasp scar',
      'has sand always clinging to their boots',
      'has tiny burn pinpricks on both forearms',
      'has an old dueling scar across the cheek',
      'has a permanently raised shoulder',
      'has smoke-gray irises',
      'has a thin braid threaded with feathers',
      'has a chipped jawline from an old break',
      'has a fingerless glove hiding a missing knuckle',
      'has a constant smell of clove and ash',
      'has a rough stutter when tired',
      'has a deep laugh that turns into a cough',
      'has a tiny scar at the corner of each lip',
    ],
    personalityQuirk: [
      'whispers when excited',
      'never breaks eye contact',
      'laughs at inappropriate moments',
      'over-explains simple ideas',
      'answers questions with questions',
      'collects tiny trinkets',
      'always negotiates',
      'quotes old proverbs',
      'apologizes before disagreeing',
      'treats every meeting like a formal ceremony',
      'forgets names but remembers debts',
      'insists on exact timekeeping',
      'speaks in short, clipped sentences',
      'tells long stories before giving an answer',
      'avoids saying no directly',
      'repeats key words for emphasis',
      'is suspicious of compliments',
      'gives everyone a nickname',
      'hums while thinking',
      'interrupts to correct small details',
      'refuses to sit with their back to a door',
      'laughs quietly at private jokes',
      'speaks to animals as if they understand',
      'changes topics when uncomfortable',
      'praises people to get information',
      'distrusts written contracts',
      'trusts written contracts over people',
      'asks for a second opinion on everything',
      'always offers tea before business',
      'gets defensive when questioned',
      'goes silent when angry',
      'smiles when delivering bad news',
      'hates being touched',
      'stands uncomfortably close when speaking',
      'keeps promises obsessively',
      'breaks minor promises casually',
      'avoids eye contact when lying',
      'believes every rumor has some truth',
      'believes rumors are weapons',
      'gives blunt, brutally honest feedback',
      'softens every criticism with a compliment',
      'avoids conflict until it explodes',
      'seeks conflict to test people',
      'over-prepares for simple tasks',
      'improvises everything at the last second',
      'speaks in metaphors',
      'takes jokes literally',
      'loves puns and cannot resist them',
      'asks personal questions too quickly',
      'never asks personal questions',
      'is deeply superstitious',
      'dismisses superstition as nonsense',
      'keeps score in every relationship',
      'forgives quickly but never forgets',
      'forgets slights within minutes',
      'hoards favors for leverage',
      'repays favors immediately',
      'mirrors the mood of whoever they face',
      'tries to dominate every conversation',
      'avoids leadership even when qualified',
      'volunteers for dangerous tasks impulsively',
      'never volunteers and must be pushed',
      'exaggerates achievements',
      'downplays achievements',
      'tests strangers with small lies',
      'tells uncomfortable truths without warning',
      'constantly plans escape routes',
      'acts as if nothing can go wrong',
      'refuses to eat in front of strangers',
      'eats while discussing grim topics',
      'admires authority figures',
      'reflexively challenges authority',
      'frames advice as riddles',
      'gives step-by-step instructions for everything',
      'fixates on fairness',
      'prioritizes results over fairness',
      'is fiercely loyal once trust is earned',
      'changes loyalties when circumstances shift',
      'seeks praise for every contribution',
      'avoids praise and redirects credit',
      'treats every deal as temporary',
      'treats every handshake as sacred',
      'panics when plans change',
      'thrives in chaos',
      'jokes to defuse tension',
      'uses silence to pressure others',
      'needs to have the last word',
      'lets others have the last word but keeps score',
      'is curious to the point of rudeness',
      'is private to the point of secrecy',
      'gives advice nobody asked for',
      'asks advice but rarely follows it',
      'gets sentimental about old places',
      'refuses to dwell on the past',
      'is convinced fate guides their choices',
      'believes only effort matters',
      'sees patterns everywhere, even false ones',
      'insists on testing every assumption',
      'keeps an emotional distance in groups',
      'becomes overly attached to new allies',
      'taps a rhythm on nearby surfaces while listening',
      'starts every sentence with "listen"',
      'drops their voice to a dramatic whisper for mundane topics',
      'over-pronounces noble titles for comedic effect',
      'snorts when trying not to laugh',
      'greets people with elaborate bows regardless of status',
      'misquotes famous sayings confidently',
      'narrates their own actions under their breath',
      'gestures wildly and nearly hits bystanders',
      'maintains a stage voice even in private',
      'adds sound effects to stories',
      'claps once before making a point',
      'winks after saying anything suspicious',
      'speaks in a soothing bedtime tone during arguments',
      'stretches every vowel when excited',
      'uses formal courtroom language in taverns',
      'squints theatrically before answering simple questions',
      'points with their whole hand like a tour guide',
      'laughs before finishing their own jokes',
      'treats introductions like a game show announcement',
      'uses two different accents depending on mood',
      'whistles between sentences',
      'gasp-laughs at tiny inconveniences',
      'keeps saying "between us" in crowded rooms',
      'counts on fingers while speaking, even for obvious numbers',
      'announces "plot twist" when plans change',
      'responds to insults with polite applause',
      'leans in too far when sharing gossip',
      'bows to inanimate objects after bumping into them',
      'answers yes-or-no questions with long prologues',
      'imitates voices of people they just met',
      'adds unnecessary dramatic pauses',
      'clicks their tongue when unconvinced',
      'uses "my friend" for people they clearly distrust',
      'talks faster the more nervous they get',
      'drawls slowly when they are lying',
      'giggles at their own ominous warnings',
      'salutes children as if they are generals',
      'refers to everyone by occupation instead of name',
      'says "respectfully" before being very disrespectful',
      'ends statements like they are asking questions',
      'pronounces common words incorrectly and refuses correction',
      'snaps fingers to punctuate each idea',
      'hums fanfares for entering and exiting rooms',
      'cups a hand to ear dramatically when confused',
      'makes eye contact with everyone before telling a joke',
      'tries to whisper and fails loudly',
      'acts offended when people do not laugh immediately',
      'uses three synonyms in a row to sound impressive',
      'calls awkward silences "strategic pauses"',
      'stares at the sky while pretending to remember facts',
      'talks to themselves while making decisions',
      'declares every meal "a tactical feast"',
      'gives pep talks to strangers mid-conversation',
      'switches to rhyme when they are flustered',
      'pronounces names differently each time',
      'accidentally invents new idioms',
      'asks rhetorical questions and then answers them anyway',
      'keeps saying "short version" then gives the long one',
      'chuckles ominously at harmless comments',
      'uses a conspiratorial whisper for weather reports',
      'holds invisible props while telling stories',
      'repeats the last word of others for emphasis',
      'does finger-guns after successful negotiations',
      'reacts to minor surprises like a staged tragedy',
      'applauds good ideas with tiny jazz hands',
      'announces bathroom breaks like royal decrees',
      'exaggerates regional slang to sound local',
      'gives everyone unsolicited stage directions',
      'insists on one-liners after every victory',
      'speaks with perfect calm while doing chaotic things',
      'sings questions instead of asking them',
      'mishears words and runs with the misunderstanding',
      'does impressions of monsters to lighten the mood',
      'calls every map "the dramatic reveal"',
      'pats pockets loudly while pretending to search for wisdom',
      'quotes fake ancestors for authority',
      'confuses metaphors in spectacular ways',
      'asks for a drumroll before giving mundane updates',
      'nods intensely during their own speeches',
      'uses villain laughter when pleased with bargains',
      'greets enemies with cheerful small talk',
      'says "not to panic" right before panicking',
      'mimics trumpet sounds for heroic moments',
      'gasps theatrically at their own reflection',
      'addresses groups as "my distinguished audience"',
      'invents catchphrases that never catch on',
      'uses pet names for dangerous creatures',
      'holds up one finger for too long before speaking',
      'talks in alliteration whenever possible',
      'calls awkward moments "character building"',
      'uses courtroom objections in casual debate',
      'declares every rumor "breaking news"',
      'turns ordinary greetings into formal proclamations',
      'laughs like a villain then apologizes sweetly',
      'gives weather updates with battlefield urgency',
      'uses hand puppets made from gloves when bored',
      'refers to plans as episodes in an ongoing saga',
      'ends tense conversations with a cheerful thumbs-up',
      'dramatically clears throat before trivial comments',
    ],
  };

  static NPC_ATTITUDE_WEIGHTS = {
    supportive: 10,
    friendly: 20,
    indifferent: 35,
    suspicious: 25,
    hostile: 10,
  };

  static NPC_RACE_DATA = {
    human: {
      firstNames: NPC_NAME_CATALOG.human.firstNames,
      lastNames: NPC_NAME_CATALOG.human.lastNames,
      age: { min: 18, max: 75 },
    },
    elf: {
      firstNames: NPC_NAME_CATALOG.elf.firstNames,
      lastNames: NPC_NAME_CATALOG.elf.lastNames,
      age: { min: 60, max: 450 },
    },
    dwarf: {
      firstNames: NPC_NAME_CATALOG.dwarf.firstNames,
      lastNames: NPC_NAME_CATALOG.dwarf.lastNames,
      age: { min: 35, max: 320 },
    },
    halfling: {
      firstNames: NPC_NAME_CATALOG.halfling.firstNames,
      lastNames: NPC_NAME_CATALOG.halfling.lastNames,
      age: { min: 20, max: 150 },
    },
    tiefling: {
      firstNames: NPC_NAME_CATALOG.tiefling.firstNames,
      lastNames: NPC_NAME_CATALOG.tiefling.lastNames,
      age: { min: 18, max: 110 },
    },
    orc: {
      firstNames: NPC_NAME_CATALOG.orc.firstNames,
      lastNames: NPC_NAME_CATALOG.orc.lastNames,
      age: { min: 14, max: 75 },
    },
    goblin: {
      firstNames: NPC_NAME_CATALOG.goblin.firstNames,
      lastNames: NPC_NAME_CATALOG.goblin.lastNames,
      age: { min: 8, max: 60 },
    },
    goliath: {
      firstNames: NPC_NAME_CATALOG.goliath.firstNames,
      lastNames: NPC_NAME_CATALOG.goliath.lastNames,
      age: { min: 16, max: 95 },
    },
    gnome: {
      firstNames: NPC_NAME_CATALOG.gnome.firstNames,
      lastNames: NPC_NAME_CATALOG.gnome.lastNames,
      age: { min: 30, max: 400 },
    },
    dragonborn: {
      firstNames: NPC_NAME_CATALOG.dragonborn.firstNames,
      lastNames: NPC_NAME_CATALOG.dragonborn.lastNames,
      age: { min: 15, max: 90 },
    },
  };

  static RACE_OPTIONS = Object.keys(this.NPC_RACE_DATA).map((race) => ({
    value: race,
    label: race[0].toUpperCase() + race.slice(1),
  }));

  static BASE_NPC_RACE_WEIGHTS_BY_HABITAT = {
    urban: {
      human: 24,
      dwarf: 12,
      halfling: 10,
      elf: 10,
      tiefling: 8,
      gnome: 12,
      dragonborn: 8,
      goblin: 8,
      orc: 4,
      goliath: 4,
    },
    forest: {
      elf: 22,
      human: 14,
      halfling: 12,
      tiefling: 8,
      dwarf: 8,
      gnome: 14,
      goblin: 8,
      orc: 6,
      goliath: 4,
      dragonborn: 4,
    },
    cave: {
      dwarf: 16,
      human: 14,
      tiefling: 10,
      elf: 8,
      halfling: 8,
      orc: 12,
      goblin: 12,
      dragonborn: 8,
      goliath: 8,
      gnome: 4,
    },
  };

  static BASE_NPC_CLASS_WEIGHTS_BY_HABITAT = {
    urban: {
      fighter: 16,
      rogue: 18,
      wizard: 16,
      cleric: 14,
      bard: 18,
      paladin: 10,
      ranger: 8,
    },
    forest: {
      ranger: 24,
      druid: 24,
      fighter: 14,
      rogue: 12,
      barbarian: 10,
      cleric: 8,
      monk: 8,
    },
    cave: {
      fighter: 22,
      rogue: 18,
      cleric: 14,
      wizard: 14,
      paladin: 12,
      barbarian: 12,
      ranger: 8,
    },
  };

  static NPC_RACE_WEIGHTS_BY_HABITAT = {
    ...this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT,
    arctic: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.cave,
    desert: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.cave,
    jungle: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.forest,
    volcanic: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.cave,
    roadside: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.urban,
    mountain: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.cave,
    swamp: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.forest,
    plains: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.forest,
    coast: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.urban,
  };

  static NPC_CLASS_WEIGHTS_BY_HABITAT = {
    ...this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT,
    arctic: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.cave,
    desert: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.cave,
    jungle: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.forest,
    volcanic: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.cave,
    roadside: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.urban,
    mountain: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.cave,
    swamp: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.forest,
    plains: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.forest,
    coast: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.urban,
  };

  static CLASS_OPTIONS = Array.from(
    new Set(Object.values(this.NPC_CLASS_WEIGHTS_BY_HABITAT).flatMap((weights) => Object.keys(weights))),
  ).map((className) => ({
    value: className,
    label: className[0].toUpperCase() + className.slice(1),
  }));

  static NPC_PROFESSIONS = [
    'alchemist',
    'animal handler',
    'apothecary',
    'apprentice mage',
    'architect',
    'armorer',
    'arcanist',
    'astrologer',
    'baker',
    'bandit scout',
    'bard',
    'barber',
    'blacksmith',
    'boatwright',
    'bookbinder',
    'brewer',
    'bricklayer',
    'butcher',
    'caravan guard',
    'carpenter',
    'cartographer',
    'chandler',
    'city watch officer',
    'clerk',
    'clockmaker',
    'cook',
    'courier',
    'diplomat',
    'dockworker',
    'dragon scholar',
    'druid acolyte',
    'enchanter',
    'engineer',
    'falconer',
    'farmer',
    'fence',
    'ferryman',
    'fisher',
    'fletcher',
    'fortune teller',
    'gemcutter',
    'glassblower',
    'grave warden',
    'guard captain',
    'guild artisan',
    'harbor master',
    'healer',
    'herbalist',
    'historian',
    'hunter',
    'illustrator',
    'innkeeper',
    'jailer',
    'jeweler',
    'judge',
    'lamplighter',
    'librarian',
    'locksmith',
    'lumberjack',
    'mage hunter',
    'mason',
    'mercenary',
    'merchant',
    'messenger',
    'miller',
    'miner',
    'minstrel',
    'monster tracker',
    'navigator',
    'night watchman',
    'outfitter',
    'painter',
    'physician',
    'pilgrim guide',
    'potter',
    'priest',
    'quartermaster',
    'ranger',
    'rat catcher',
    'ruin scholar',
    'sailor',
    'scribe',
    'sculptor',
    'ship captain',
    'shipwright',
    'smuggler',
    'stablemaster',
    'stonemason',
    'tanner',
    'tax collector',
    'teacher',
    'thief',
    'tinker',
    'town crier',
    'treasure hunter',
    'trapper',
    'undertaker',
    'vintner',
    'weaver',
    'woodcarver',
  ];

  static weightedPick(entries) {
    const validEntries = entries.filter((entry) => entry.weight > 0);
    if (validEntries.length === 0) {
      return null;
    }

    const totalWeight = validEntries.reduce((sum, entry) => sum + entry.weight, 0);
    let roll = Math.random() * totalWeight;

    for (const entry of validEntries) {
      roll -= entry.weight;
      if (roll <= 0) {
        return entry.value;
      }
    }

    return validEntries[validEntries.length - 1].value;
  }

  static getRandomFromList(list) {
    return list[Math.floor(Math.random() * list.length)];
  }

  static randomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  static generateNpc({ habitat, attitude, race: selectedRace, characterClass: selectedClass }) {
    const resolvedAttitude = attitude || this.weightedPick(
      this.npcOptions.hostility.map((entry) => ({
        value: entry.attitude,
        weight: this.NPC_ATTITUDE_WEIGHTS[entry.attitude] || 1,
      })),
    );

    const hostilityDetails = this.npcOptions.hostility.find(
      (entry) => entry.attitude === resolvedAttitude,
    );

    const raceWeights = this.NPC_RACE_WEIGHTS_BY_HABITAT[habitat] || this.NPC_RACE_WEIGHTS_BY_HABITAT.urban;
    const race = selectedRace || this.weightedPick(
      Object.entries(raceWeights).map(([raceName, weight]) => ({
        value: raceName,
        weight,
      })),
    );

    const classWeights = this.NPC_CLASS_WEIGHTS_BY_HABITAT[habitat] || this.NPC_CLASS_WEIGHTS_BY_HABITAT.urban;
    const characterClass = selectedClass || this.weightedPick(
      Object.entries(classWeights).map(([className, weight]) => ({
        value: className,
        weight,
      })),
    );

    const raceData = this.NPC_RACE_DATA[race] || this.NPC_RACE_DATA.human;
    const firstName = this.getRandomFromList(raceData.firstNames);
    const lastName = this.getRandomFromList(raceData.lastNames);
    const age = this.randomInt(raceData.age.min, raceData.age.max);
    return {
      name: `${firstName} ${lastName}`,
      race,
      characterClass,
      age,
      habitat,
      attitude: hostilityDetails.attitude,
      socialChecks: hostilityDetails.socialChecks,
      dc: hostilityDetails.dc,
      motivation: this.getRandomFromList(this.npcOptions.motivation),
      profession: this.getRandomFromList(this.NPC_PROFESSIONS),
      physicalQuirk: this.getRandomFromList(this.npcOptions.physicalQuirk),
      personalityQuirk: this.getRandomFromList(this.npcOptions.personalityQuirk),
    };
  }
}

export default NpcGenerator;
