import { NPC_NAME_CATALOG } from '../data/npcNameCatalogue';
import { EVENT_HABITAT_OPTIONS } from '../data/habitatOptions';

class NpcGenerator {
  static HABITAT_OPTIONS = [
    { value: '', label: 'Any Habitat' },
    ...EVENT_HABITAT_OPTIONS,
  ];
  static GENDER_OPTIONS = [
    { value: '', label: 'Auto (Random)' },
    { value: 'male', label: 'Male' },
    { value: 'female', label: 'Female' },
  ];

  static npcOptions = {
    hostility: [
      { attitude: 'supportive', socialChecks: 'very easy', dc: 5 },
      { attitude: 'friendly', socialChecks: 'easy', dc: 10 },
      { attitude: 'indifferent', socialChecks: 'medium', dc: 15 },
      { attitude: 'suspicious', socialChecks: 'hard', dc: 20 },
      { attitude: 'hostile', socialChecks: 'very hard', dc: 25 },
    ],
    motivation: ['money', 'help', 'survival', 'status', 'relationships', 'knowledge', 'power', 'revenge', 'ideology'],
    physicalQuirk: [
      'has a silver tooth',
      'keeps one eye half-closed',
      'has a noticeable limp',
      'wears mismatched gloves',
      'has burn scars on one hand',
      'sports elaborate braided hair',
      'has ink-stained fingers',
      'wears a cracked monocle',
      'always smells of lavender oil',
      'has a chipped tusk',
      'wears one boot taller than the other',
      'has a faded military tattoo',
      'has a missing fingertip',
      'wears too many rings',
      'has a permanent squint',
      'has a shaved stripe through one eyebrow',
      'has frostbitten ears',
      'has soot-blackened nails',
      'has a tiny bell sewn into their cloak',
      'has a carved wooden prosthetic hand',
      'has a scar shaped like a crescent moon',
      'has a broken nose set crooked',
      'has a patchwork coat of many fabrics',
      'has one gold-painted fingernail',
      'has mismatched eye colors',
      'has a deep smoker cough',
      'has hands calloused like stone',
      'has a constantly twitching left eye',
      'has a jagged ear notch',
      'has bright dye-stained hair tips',
      'has knuckles wrapped in old linen',
      'has a faint glow in their pupils',
      'has a permanently hoarse whisper',
      'has a tattooed map on one forearm',
      'has braided beard beads',
      'has a chipped horn',
      'has a ritual scar across the scalp',
      'has a missing canine tooth',
      'has wrists covered in old rope marks',
      'has a heavy perfume that masks smoke',
      'has dirt permanently under the nails',
      'has a ceremonial face paint stripe',
      'has an iron brace on one knee',
      'has a velvet eyepatch',
      'has a hand tremor when idle',
      'has a polished bone hairpin',
      'has a limp that vanishes when running',
      'has a serpentine tattoo around the neck',
      'has an old arrow scar in the shoulder',
      'has thick spectacles with cracked lenses',
      'has chalk dust on every sleeve',
      'has a soot-smudged jawline',
      'has a braided cord tied to one wrist',
      'has a ceremonial nose ring',
      'has a permanent grin line scar',
      'has one sleeve pinned at the elbow',
      'has polished metal teeth caps',
      'has a pitted pox-marked complexion',
      'has wind-chapped lips year-round',
      'has a tiny rune branded behind one ear',
      'has a chain of tiny charms around one ankle',
      'has a wolf bite scar on the calf',
      'has a shaved head except for one braid',
      'has bright freckles across the nose',
      'has hands that are always cold',
      'has permanently singed eyebrows',
      'has a glove covering a tattooed palm sigil',
      'has stained teeth from herbal chewing',
      'has an ornate cane despite no obvious injury',
      'has a stitched seam in one ear',
      'has heavy rings in both ears',
      'has a weathered sailor knot tattoo',
      'has a jagged scar over one collarbone',
      'has an old dueling scar across the cheek',
      'has smoke-gray irises',
      'has a thin braid threaded with feathers',
      'has a chipped jawline from an old break',
      'has a fingerless glove hiding a missing knuckle',
      'has a constant smell of clove and ash',
      'has a deep laugh that turns into a cough',
      'has a tiny scar at the corner of each lip',
      'has one eyebrow dyed an unnatural color',
      'has a cracked crystal lens in one eye socket',
      'has a belt made from old map scraps',
      'has tiny charms braided into their eyelashes',
      'has a travel cloak lined with stage glitter',
      'has a boot heel full of tiny pebbles that rattle',
      'has a scar shaped like a lightning fork',
      'has bite marks on a gauntlet they refuse to explain',
      'has one ear pierced with fishing hooks',
      'has a mustache waxed into ridiculous spirals',
      'has a carefully polished dent in their helmet',
      'has a shirt always buttoned one hole wrong',
      'has an elegant cane topped with a carved frog',
      'has a cuff stitched with tiny laughing skulls',
      'has a necklace made of mismatched keys',
      'has one glove embroidered with fake royal seals',
      'has soot on their cheek no matter how often they wash',
      'has a thumb permanently inked black from seals',
      'has a subtle whistle in their breathing after running',
      'has one horn wrapped in ceremonial thread',
      'has weather beads tied into their hair',
      'has knuckles tattooed with tiny constellations',
      'has one shoulder pauldron from an entirely different suit',
      'has a scar that resembles a smile when they frown',
      'has a velvet collar full of hidden pocket notes',
      'has boots polished to mirror shine but scuffed toes',
      'has one finger covered in counting rings',
      'has a cloak clasp shaped like a staring eye',
      'has an old duel ribbon tied to their sword belt',
      'has a glove stuffed with lucky rabbit ears',
      'has a laugh-snort that shakes their shoulders',
      'has a dramatic widow peak in their hairline',
      'has one sleeve sewn with tiny bells they forgot to remove',
      'has an embroidered handkerchief tucked in every pocket',
      'has freckles that form a near-perfect arrow',
      'has one boot painted with marching tally marks',
      'has a silver tooth carved with a tiny rune',
      'has an eye scar that only shows in moonlight',
      'has a travel hat patched with casino chips',
      'has a belt buckle shaped like a roaring lion',
      'has a gauntlet signed by famous duelists',
      'has one ear cuff that chimes in strong wind',
      'has gloves stitched from different shades of leather',
      'has a polished shoulder scar from old armor rub',
      'has one boot lace replaced with fishing line',
      'has a ring that leaves green stains on their finger',
      'has a tiny compass tattoo behind their thumb',
      'has a necklace of carved bone dice',
      'has a monogrammed scarf that was clearly stolen',
      'has a dramatic cape that is one size too long',
      'has a carved coin lodged in an old scar',
      'has one pupil shaped like a star',
      'has a false nose bridge from an old break',
      'has a jaw tattoo hidden beneath stubble',
      'has chalk tally marks on their glove cuff',
      'has teeth capped in brass with tiny etchings',
      'has one cheek permanently windburned',
      'has a nose ring made from lockpick wire',
      'has old rope burns circling both forearms',
      'has one eyebrow slit in three places',
      'has a ceremonial sash frayed to threads',
      'has a tiny spoon pinned to their lapel',
      'has one boot toe reinforced in copper',
      'has hands stained with berry dye',
      'has laugh lines deeper on only one side',
      'has a knotted scar crossing their palm',
      'has a collar pin shaped like a moth',
      'has one ear that never stops twitching',
      'has a cloak hem burned into lace-like holes',
      'has bright amber eyes that look reflective at dusk',
      'has a theatrical beauty mark drawn slightly off center',
      'has a lisp',
      'has a strange foreign accent',
      'has a twitch',
      'spits a lot when talking',
      'has a southern accent',
      'stutters heavily when nervous',
      'has chronic body odor',
      'is hunchbacked, crippled, or one-legged',
      'falls asleep randomly (narcoleptic)',
      'clears their throat an awful lot',
      'is always scratching',
      'sneezes loudly and often',
      'constantly scratches a large exposed belly',
      'hocks up phlegm in the middle of conversation',
      'farts loudly at inappropriate times',
      'loudly exhales in the middle of sentences',
      'has a facial tic',
      'speaks very slowly',
      'is unusually dirty for the circumstances',
      'is unusually clean for the circumstances',
      'has a knockout figure or adonis build',
      'is unusually tall for their people',
      'is unusually short for their people',
      'is especially well-dressed',
      'has a terrible sense of fashion',
      'is missing a body part',
      'has noticeable scars',
      'requires a walking aid',
      'is suffering from disease',
      'has a pronounced hunchback',
      'is unusually young for their role',
      'is unusually old for their role',
      'is in poor health',
      'is perpetually sleepy',
    ],
    personalityQuirk: [
      'whispers when excited',
      'rhymes every sentence',
      'never breaks eye contact',
      'laughs at inappropriate moments',
      'over-explains simple ideas',
      'answers questions with questions',
      'collects tiny trinkets',
      'always negotiates',
      'quotes old proverbs',
      'apologizes before disagreeing',
      'forgets names but remembers debts',
      'insists on exact timekeeping',
      'speaks in short, clipped sentences',
      'tells long stories before giving an answer',
      'avoids saying no directly',
      'is suspicious of compliments',
      'gives everyone a nickname',
      'hums while thinking',
      'interrupts to correct small details',
      'refuses to sit with their back to a door',
      'speaks to animals as if they understand',
      'changes topics when uncomfortable',
      'praises people to get information',
      'asks for a second opinion on everything',
      'always offers tea before business',
      'goes silent when angry',
      'smiles when delivering bad news',
      'keeps promises obsessively',
      'breaks minor promises casually',
      'believes every rumor has some truth',
      'gives blunt, brutally honest feedback',
      'softens every criticism with a compliment',
      'avoids conflict until it explodes',
      'seeks conflict to test people',
      'over-prepares for simple tasks',
      'improvises everything at the last second',
      'speaks in metaphors',
      'takes jokes literally',
      'loves puns and cannot resist them',
      'is deeply superstitious',
      'dismisses superstition as nonsense',
      'fixates on fairness',
      'prioritizes results over fairness',
      'is fiercely loyal once trust is earned',
      'changes loyalties when circumstances shift',
      'panics when plans change',
      'thrives in chaos',
      'jokes to defuse tension',
      'uses silence to pressure others',
      'is curious to the point of rudeness',
      'is private to the point of secrecy',
      'gives advice nobody asked for',
      'asks advice but rarely follows it',
      'keeps an emotional distance in groups',
      'becomes overly attached to new allies',
      'greets people with elaborate bows regardless of status',
      'misquotes famous sayings confidently',
      'narrates their own actions under their breath',
      'gestures wildly and nearly hits bystanders',
      'adds sound effects to stories',
      'claps once before making a point',
      'winks after saying anything suspicious',
      'stretches every vowel when excited',
      'uses formal courtroom language in taverns',
      'squints theatrically before answering simple questions',
      'points with their whole hand like a tour guide',
      'laughs before finishing their own jokes',
      'whistles between sentences',
      'responds to insults with polite applause',
      'bows to inanimate objects after bumping into them',
      'answers yes-or-no questions with long prologues',
      'adds unnecessary dramatic pauses',
      'talks faster the more nervous they get',
      'salutes children as if they are generals',
      'says respectfully before being very disrespectful',
      'pronounces common words incorrectly and refuses correction',
      'hums fanfares for entering and exiting rooms',
      'tries to whisper and fails loudly',
      'uses three synonyms in a row to sound impressive',
      'calls awkward silences strategic pauses',
      'talks to themselves while making decisions',
      'declares every meal a tactical feast',
      'switches to rhyme when flustered',
      'accidentally invents new idioms',
      'asks rhetorical questions then answers them anyway',
      'keeps saying short version then gives the long one',
      'chuckles ominously at harmless comments',
      'holds invisible props while telling stories',
      'does finger-guns after successful negotiations',
      'applauds good ideas with tiny jazz hands',
      'announces bathroom breaks like royal decrees',
      'gives everyone unsolicited stage directions',
      'insists on one-liners after every victory',
      'sings questions instead of asking them',
      'mishears words and commits to the misunderstanding',
      'does monster impressions to lighten the mood',
      'asks for a drumroll before mundane updates',
      'greets enemies with cheerful small talk',
      'says not to panic right before panicking',
      'gasps theatrically at their own reflection',
      'addresses groups as my distinguished audience',
      'invents catchphrases that never catch on',
      'uses pet names for dangerous creatures',
      'talks in alliteration whenever possible',
      'uses courtroom objections in casual debates',
      'declares every rumor breaking news',
      'laughs like a villain then apologizes sweetly',
      'turns ordinary greetings into formal proclamations',
      'uses hand puppets made from gloves when bored',
      'ends tense conversations with a cheerful thumbs-up',
      'insists on naming every plan before it begins',
      'insists on asking for applause after practical ideas',
      'insists on starting pep talks at awkward times',
      'insists on whispering obvious facts as if they are secrets',
      'insists on treating gossip like confidential intelligence',
      'insists on inventing slogans for basic chores',
      'insists on asking if danger can wait until after lunch',
      'insists on using finger quotes for ordinary words',
      'insists on treating checklists as sacred documents',
      'insists on calling cleanup a post-battle aesthetic phase',
      'insists on greeting rivals with cheerful small talk',
      'insists on offering confidence ratings after introductions',
      'insists on keeping a running tally of dramatic exits',
      'gives weather updates with battlefield urgency',
      'requests witness signatures for simple promises',
      'tries to rename everyone with tactical codenames',
      'rates plans on a scale from tragic to iconic',
      'treats spilled tea like a strategic omen',
      'declares snack breaks as official intermissions',
      'insists every hallway walk is a ceremonial procession',
      'asks if every meeting has a sequel',
      'starts countdowns for no clear reason',
      'offers post-conversation recap summaries no one requested',
      'tries to interview bystanders for an imaginary newspaper',
      'asks for rehearsal before difficult conversations',
      'labels all pouches with dramatic titles',
      'thanks doors after walking through them',
      'asks if everyone is emotionally hydrated',
      'frames minor mistakes as field experiments',
      'calls boredom a tactical vulnerability',
      'describes ordinary timing as miraculous fate',
      'gives morale briefings at random',
      'asks people to repeat puns for documentation',
      'gets stressed very easily',
      'gets angered easily',
      'does not read social cues well',
      'interrupts people too much',
      'is very shy around strangers',
      'talks too loudly without noticing',
      'avoids difficult conversations',
      'takes criticism very personally',
      'worries constantly about small problems',
      'is quick to assume the worst',
      'overthinks every decision',
      'needs frequent reassurance',
      'is impatient when waiting',
      'gets defensive when corrected',
      'holds grudges for a long time',
      'forgives too quickly',
      'trusts people too easily',
      'trusts almost no one',
      'is easily embarrassed',
      'is easily distracted',
      'changes their mind often',
      'struggles to make decisions',
      'second-guesses themselves constantly',
      'is very stubborn once decided',
      'is overly competitive',
      'hates losing even small games',
      'tries too hard to be liked',
      'seeks approval from authority figures',
      'needs to control every plan',
      'panics when plans fall apart',
      'avoids eye contact when nervous',
      'talks rapidly when anxious',
      'goes completely quiet when upset',
      'apologizes even when not at fault',
      'struggles to say no',
      'says no to everything at first',
      'takes jokes too seriously',
      'has a very dry sense of humor',
      'uses humor to avoid serious topics',
      'becomes sarcastic under stress',
      'is blunt without meaning to offend',
      'is overly polite in tense moments',
      'gets attached to people quickly',
      'keeps emotional distance from others',
      'is uncomfortable with compliments',
      'boasts to hide insecurity',
      'avoids taking responsibility for mistakes',
      'admits mistakes immediately',
      'acts confident but doubts themselves',
      'needs routines and dislikes surprises',
      'uses really bad grammar',
      'is aloof and stand-offish',
      'uses a lot of metaphors',
      'forgets what they are reading or saying mid-sentence',
      'makes bets about almost everything',
      'uses a silly imitation accent when speaking',
      'is romantically involved with someone from your past',
      'owes you money',
      'hates adventurers because a loved one died adventuring',
      'is jealous of the PCs looks, wealth, or power',
      'is pious to a dangerous extreme',
      'is a treasure hunter',
      'is a kleptomaniac who steals constantly',
      'is verbally abusive to people of lesser station',
      'always talks in rhymes',
      'creeps toward women in an unsettling way',
      'is melodramatic about everything',
      'is obsessed with avoiding germs and dirt',
      'is rude to people they consider dirty',
      'constantly makes sexual innuendos',
      'uses bad puns constantly',
      'flirts a lot',
      'only does things in threes or multiples of three',
      'has no sense of humor despite constant jokes',
      'constantly strokes a lucky charm',
      'has a fear of leaving the city or country',
      'is a voyeur or stalker',
      'is drunk or alcoholic',
      'is prejudiced',
      'is a drug addict',
      'is boisterous and cocky',
      'is lazy',
      'is rude or sarcastic',
      'is cowardly and jumpy',
      'is highly enthusiastic',
      'is superstitious',
      'has noble status and acts like it',
      'is in debt',
      'is a blood relative of a known NPC',
      'is easily distracted and lost in thought',
      'idolizes and gushes about someone or something',
      'despises and opposes someone or something',
      'is obsessed with cleanliness',
      'is inept but wants to join the adventure',
      'is too honest for their own good',
      'likes to sound smart',
      'breaks into song unexpectedly',
      'lies about everything',
    ],
  };

  static NPC_ATTITUDE_WEIGHTS = {
    supportive: 10,
    friendly: 20,
    indifferent: 35,
    suspicious: 25,
    hostile: 10,
  };

  static NPC_RACE_DATA = {
    human: {
      firstNames: NPC_NAME_CATALOG.human.firstNames,
      lastNames: NPC_NAME_CATALOG.human.lastNames,
      age: { min: 18, max: 75 },
    },
    elf: {
      firstNames: NPC_NAME_CATALOG.elf.firstNames,
      lastNames: NPC_NAME_CATALOG.elf.lastNames,
      age: { min: 60, max: 450 },
    },
    dwarf: {
      firstNames: NPC_NAME_CATALOG.dwarf.firstNames,
      lastNames: NPC_NAME_CATALOG.dwarf.lastNames,
      age: { min: 35, max: 320 },
    },
    halfling: {
      firstNames: NPC_NAME_CATALOG.halfling.firstNames,
      lastNames: NPC_NAME_CATALOG.halfling.lastNames,
      age: { min: 20, max: 150 },
    },
    tiefling: {
      firstNames: NPC_NAME_CATALOG.tiefling.firstNames,
      lastNames: NPC_NAME_CATALOG.tiefling.lastNames,
      age: { min: 18, max: 110 },
    },
    orc: {
      firstNames: NPC_NAME_CATALOG.orc.firstNames,
      lastNames: NPC_NAME_CATALOG.orc.lastNames,
      age: { min: 14, max: 75 },
    },
    goblin: {
      firstNames: NPC_NAME_CATALOG.goblin.firstNames,
      lastNames: NPC_NAME_CATALOG.goblin.lastNames,
      age: { min: 8, max: 60 },
    },
    goliath: {
      firstNames: NPC_NAME_CATALOG.goliath.firstNames,
      lastNames: NPC_NAME_CATALOG.goliath.lastNames,
      age: { min: 16, max: 95 },
    },
    gnome: {
      firstNames: NPC_NAME_CATALOG.gnome.firstNames,
      lastNames: NPC_NAME_CATALOG.gnome.lastNames,
      age: { min: 30, max: 400 },
    },
    dragonborn: {
      firstNames: NPC_NAME_CATALOG.dragonborn.firstNames,
      lastNames: NPC_NAME_CATALOG.dragonborn.lastNames,
      age: { min: 15, max: 90 },
    },
  };

  static RACE_OPTIONS = Object.keys(this.NPC_RACE_DATA).map((race) => ({
    value: race,
    label: race[0].toUpperCase() + race.slice(1),
  }));

  static BASE_NPC_RACE_WEIGHTS_BY_HABITAT = {
    urban: {
      human: 24,
      dwarf: 12,
      halfling: 10,
      elf: 10,
      tiefling: 8,
      gnome: 12,
      dragonborn: 8,
      goblin: 8,
      orc: 4,
      goliath: 4,
    },
    forest: {
      elf: 22,
      human: 14,
      halfling: 12,
      tiefling: 8,
      dwarf: 8,
      gnome: 14,
      goblin: 8,
      orc: 6,
      goliath: 4,
      dragonborn: 4,
    },
    cave: {
      dwarf: 16,
      human: 14,
      tiefling: 10,
      elf: 8,
      halfling: 8,
      orc: 12,
      goblin: 12,
      dragonborn: 8,
      goliath: 8,
      gnome: 4,
    },
  };

  static BASE_NPC_CLASS_WEIGHTS_BY_HABITAT = {
    urban: {
      rogue: 18,
      wizard: 16,
      cleric: 14,
      bard: 18,
      paladin: 10,
      ranger: 8,
    },
    forest: {
      ranger: 24,
      druid: 24,
      rogue: 12,
      barbarian: 10,
      cleric: 8,
    },
    cave: {
      rogue: 18,
      cleric: 14,
      wizard: 14,
      paladin: 12,
      barbarian: 12,
      ranger: 8,
    },
  };

  static NPC_RACE_WEIGHTS_BY_HABITAT = {
    ...this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT,
    arctic: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.cave,
    desert: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.cave,
    jungle: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.forest,
    volcanic: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.cave,
    roadside: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.urban,
    mountain: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.cave,
    swamp: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.forest,
    plains: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.forest,
    coast: this.BASE_NPC_RACE_WEIGHTS_BY_HABITAT.urban,
  };

  static NPC_CLASS_WEIGHTS_BY_HABITAT = {
    ...this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT,
    arctic: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.cave,
    desert: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.cave,
    jungle: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.forest,
    volcanic: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.cave,
    roadside: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.urban,
    mountain: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.cave,
    swamp: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.forest,
    plains: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.forest,
    coast: this.BASE_NPC_CLASS_WEIGHTS_BY_HABITAT.urban,
  };

  static CLASS_OPTIONS = Array.from(
    new Set(Object.values(this.NPC_CLASS_WEIGHTS_BY_HABITAT).flatMap((weights) => Object.keys(weights))),
  ).map((className) => ({
    value: className,
    label: className[0].toUpperCase() + className.slice(1),
  }));

  static NPC_PROFESSIONS = [
    'alchemist',
    'animal handler',
    'apothecary',
    'apprentice mage',
    'architect',
    'armorer',
    'arcanist',
    'astrologer',
    'baker',
    'bandit scout',
    'bard',
    'barber',
    'blacksmith',
    'boatwright',
    'bookbinder',
    'brewer',
    'bricklayer',
    'butcher',
    'caravan guard',
    'carpenter',
    'cartographer',
    'chandler',
    'city watch officer',
    'clerk',
    'clockmaker',
    'cook',
    'courier',
    'diplomat',
    'dockworker',
    'dragon scholar',
    'druid acolyte',
    'enchanter',
    'engineer',
    'falconer',
    'farmer',
    'fence',
    'ferryman',
    'fisher',
    'fletcher',
    'fortune teller',
    'gemcutter',
    'glassblower',
    'grave warden',
    'guard captain',
    'guild artisan',
    'harbor master',
    'healer',
    'herbalist',
    'historian',
    'hunter',
    'illustrator',
    'innkeeper',
    'jailer',
    'jeweler',
    'judge',
    'lamplighter',
    'librarian',
    'locksmith',
    'lumberjack',
    'mage hunter',
    'mason',
    'mercenary',
    'merchant',
    'messenger',
    'miller',
    'miner',
    'minstrel',
    'monster tracker',
    'navigator',
    'night watchman',
    'outfitter',
    'painter',
    'physician',
    'pilgrim guide',
    'potter',
    'priest',
    'quartermaster',
    'ranger',
    'rat catcher',
    'ruin scholar',
    'sailor',
    'scribe',
    'sculptor',
    'ship captain',
    'shipwright',
    'smuggler',
    'stablemaster',
    'stonemason',
    'tanner',
    'tax collector',
    'teacher',
    'thief',
    'tinker',
    'town crier',
    'treasure hunter',
    'trapper',
    'undertaker',
    'vintner',
    'weaver',
    'woodcarver',
  ];

  static weightedPick(entries) {
    const validEntries = entries.filter((entry) => entry.weight > 0);
    if (validEntries.length === 0) {
      return null;
    }

    const totalWeight = validEntries.reduce((sum, entry) => sum + entry.weight, 0);
    let roll = Math.random() * totalWeight;

    for (const entry of validEntries) {
      roll -= entry.weight;
      if (roll <= 0) {
        return entry.value;
      }
    }

    return validEntries[validEntries.length - 1].value;
  }

  static getRandomFromList(list) {
    return list[Math.floor(Math.random() * list.length)];
  }

  static randomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  static generateNpc({
    habitat,
    attitude,
    race: selectedRace,
    characterClass: selectedClass,
    gender: selectedGender,
  }) {
    const resolvedHabitat = habitat || this.getRandomFromList(
      Object.keys(this.NPC_RACE_WEIGHTS_BY_HABITAT),
    );

    const resolvedAttitude = attitude || this.weightedPick(
      this.npcOptions.hostility.map((entry) => ({
        value: entry.attitude,
        weight: this.NPC_ATTITUDE_WEIGHTS[entry.attitude] || 1,
      })),
    );

    const hostilityDetails = this.npcOptions.hostility.find(
      (entry) => entry.attitude === resolvedAttitude,
    );

    const raceWeights = this.NPC_RACE_WEIGHTS_BY_HABITAT[resolvedHabitat]
      || this.NPC_RACE_WEIGHTS_BY_HABITAT.urban;
    const race = selectedRace || this.weightedPick(
      Object.entries(raceWeights).map(([raceName, weight]) => ({
        value: raceName,
        weight,
      })),
    );

    const classWeights = this.NPC_CLASS_WEIGHTS_BY_HABITAT[resolvedHabitat]
      || this.NPC_CLASS_WEIGHTS_BY_HABITAT.urban;
    const characterClass = selectedClass || this.weightedPick(
      Object.entries(classWeights).map(([className, weight]) => ({
        value: className,
        weight,
      })),
    );

    const raceData = this.NPC_RACE_DATA[race] || this.NPC_RACE_DATA.human;
    const resolvedGender = selectedGender || this.getRandomFromList(['male', 'female']);
    const genderFirstNames = raceData.firstNames?.[resolvedGender]
      || [...(raceData.firstNames?.male || []), ...(raceData.firstNames?.female || [])];
    const firstName = this.getRandomFromList(genderFirstNames);
    const lastName = this.getRandomFromList(raceData.lastNames);
    const age = this.randomInt(raceData.age.min, raceData.age.max);
    return {
      name: `${firstName} ${lastName}`,
      gender: resolvedGender,
      race,
      characterClass,
      age,
      habitat: resolvedHabitat,
      attitude: hostilityDetails.attitude,
      socialChecks: hostilityDetails.socialChecks,
      dc: hostilityDetails.dc,
      motivation: this.getRandomFromList(this.npcOptions.motivation),
      profession: this.getRandomFromList(this.NPC_PROFESSIONS),
      physicalQuirk: this.getRandomFromList(this.npcOptions.physicalQuirk),
      personalityQuirk: this.getRandomFromList(this.npcOptions.personalityQuirk),
    };
  }
}

export default NpcGenerator;
